### ISSUE TITLE
Error integrating with TAB

### ISSUE THREAD

**Issue by wingzero54** [CivMC/NameColors#9]
[16:07:11] [Server thread/WARN]: [NameColors] Task #299 for NameColors v2.0.0-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "me.neznamy.tab.api.TablistFormatManager.setName(me.neznamy.tab.api.TabPlayer, String)" because the return value of "me.neznamy.tab.api.TabAPI.getTablistFormatManager()" is null
	at com.biggestnerd.namecolors.NameColors.lambda$updatePlayerName$2(NameColors.java:77) ~[NameColors-paper-2.0.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-372]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by Diet-Cola** [comment]
Is this frequent or once every so often?

**Comment by wingzero54** [comment]
I believe it's on startup and is why name colors aren't on the tab list

**Comment by Diet-Cola** [comment]
Cannot replicate this even when downloading the jars from CivDocker?

**Comment by Protonull** [comment]
Here's your problem [[one]](https://github.com/NEZNAMY/TAB/blob/032b0f8a41ebf821cf9a2796cb1572701e2ad203/shared/src/main/java/me/neznamy/tab/shared/TAB.java#L216=) and [[two]](https://github.com/CivMC/CivDocker/blob/3f9edc1ae4cfcbfbe91306718bc74c2ee0c3dfb3/paper/config/plugins/TAB/config.yml#L26=).

*The 'TablistFormatManager' is only registered when `tablist-name-formatting.enabled` is true and currently it's not.*

**Comment by wingzero54** [comment]
> 

Oh thank you, and I guess NameColors assumes it is enabled. Easy fix

**Comment by Protonull** [comment]
I do wonder to what extent it's necessary to interface with TAB. NameColors [hooks into CivChat2](https://github.com/CivMC/NameColors/blob/13cc684b89e73df313c5db0180683f380e92050a/paper/src/main/java/com/biggestnerd/namecolors/NameColors.java#L72-L73=) to set a custom name, but looking at [the code](https://github.com/CivMC/CivChat2/blob/d309da1ad407170cc8ddbcbeb22f3ec036987ff2/paper/src/main/java/vg/civcraft/mc/civchat2/CivChat2Manager.java#L424-L426=), it's just a map-put. What would happen if we replaced that code with a simple `player.displayName(Component.text(player.getName(), NamedTextColor.GOLD));` for example?
